FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache \
    openssl \
    zlib \
    libgcc \
    && ln -s /usr/lib/libssl.so.1.1 /usr/lib/libssl.so  # Create symlink for compatibility
WORKDIR /app


COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN npm ci

FROM base AS builder
WORKDIR /app

ARG BASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG APPLE_CLIENT_ID
ARG APPLE_CLIENT_SECRET
ARG APPLE_APP_BUNDLE_IDENTIFIER
ARG POSTMARK_SERVER_TOKEN
ARG POSTMARK_FROM_EMAIL
ARG DATABASE_URL
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_SECRET_KEY
ARG COOKIE_DOMAIN

ENV BASE_URL=$BASE_URL
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV APPLE_CLIENT_ID=$APPLE_CLIENT_ID
ENV APPLE_CLIENT_SECRET=$APPLE_CLIENT_SECRET
ENV APPLE_APP_BUNDLE_IDENTIFIER=$APPLE_APP_BUNDLE_IDENTIFIER
ENV POSTMARK_SERVER_TOKEN=$POSTMARK_SERVER_TOKEN
ENV POSTMARK_FROM_EMAIL=$POSTMARK_FROM_EMAIL
ENV DATABASE_URL=$DATABASE_URL
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV COOKIE_DOMAIN=$COOKIE_DOMAIN

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/public ./public

RUN adduser -D ghost


COPY --from=builder --chown=ghost:ghost /app/.next/standalone ./
COPY --from=builder --chown=ghost:ghost /app/.next/static ./.next/static

USER ghost

EXPOSE 3010

ENV PORT=3010
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
